Fix wrong description in meetup.rb
logstash-plugins/logstash-input-meetup pull request #8
Opened 2016-10-21 15:07 UTC by Iarwa1n

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

2016-10-21 15:12 UTC, jsvd requested changes

2016-10-21 15:12 UTC, jsvd commented on lib/logstash/inputs/meetup.rb
> +# * The `@meetupkey` represents your meetup.com API key.
can we actually remove this whole notes block? all documentation for specific fields can be included in their separate descriptions

2016-10-24 13:08 UTC, Iarwa1n commented
Looking at other plugins there seem to be no consistent rules for that so I just removed the lines as requested

2016-10-24 13:19 UTC, jsvd approved these changes

2016-10-24 13:20 UTC, closed without merging

2016-10-24 13:20 UTC, jsvd commented
@Iarwa1n thanks for the contribution 👍